name: Publish release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish dash-loading-spinners to TestPyPI and PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Update version
        run: invoke update-version $GITHUB_REF

      - name: Build package
        run: nox -s build

      - name: Publish dash-loading-spinners to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish dash-loading-spinners to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
